// AUTO-GENERATED by scripts/write-electron-env.js — do not edit manually.
// Regenerated on every `npm run build:electron:main` run.
// Source: PILOTHOUSE_SERVER_URL env var (falls back to the production default).

export const BAKED_SERVER_URL = 'https://pilothouse.replit.app';
