import { ArrowLeft } from "lucide-react";
import { useLocation } from "wouter";
import { useQuery } from "@tanstack/react-query";

const DEFAULT_CONTENT = `<p class="text-xs text-gray-500">Last Updated: July 24, 2026</p>

<h2>1. Introduction</h2>
<p>PilotHouse ("we," "us," or "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard information about Subscribers (business owners and operators) and their end customers when you use the PilotHouse platform, website, and associated applications (the "Service").</p>

<h2>2. Information We Collect</h2>
<p><strong>Subscriber Account Information:</strong></p>
<ul>
<li>Name, email address, and phone number when you create an account</li>
<li>Business name, store slug, and configuration preferences</li>
<li>Billing information processed securely through Stripe (we do not store card numbers or CVVs)</li>
<li>Subscription history and plan details</li>
<li>Communication preferences (email and SMS opt-in/opt-out)</li>
</ul>
<p><strong>Business and Operational Data (Tenant Data):</strong></p>
<ul>
<li>Product inventory, pricing, and order records entered by you or your staff</li>
<li>Customer contact records, appointment history, and loyalty credit balances managed within your account</li>
<li>Sales reports, transaction records, and analytics generated by your use of the platform</li>
<li>Staff accounts, role assignments, and access logs</li>
</ul>
<p><strong>Automatically Collected Information:</strong></p>
<ul>
<li>Device information and browser type used to access the Service</li>
<li>IP addresses (used for rate limiting and security; not stored long-term)</li>
<li>Usage data such as features accessed and actions performed within the platform</li>
<li>Push notification subscription tokens (if you opt in)</li>
</ul>

<h2>3. How We Use Your Information</h2>
<ul>
<li>To provision and maintain your PilotHouse account and subscription</li>
<li>To process subscription billing and manage payment disputes</li>
<li>To operate platform features including POS, inventory, appointments, loyalty programs, and reporting on your behalf</li>
<li>To send transactional emails (account confirmations, billing receipts, password resets, security alerts)</li>
<li>To send marketing communications about PilotHouse features and updates (only with your consent; you may opt out at any time)</li>
<li>To send SMS notifications if you have provided a phone number and consented</li>
<li>To monitor platform security, detect abuse, and enforce our Terms of Service</li>
<li>To improve our platform features and customer experience</li>
</ul>

<h2>4. Tenant Data and Your Customers</h2>
<p>As a Subscriber, you may use PilotHouse to store and manage data about your own customers ("End Customer Data"). With respect to End Customer Data:</p>
<ul>
<li>You are the data controller for your End Customer Data. PilotHouse acts as a data processor on your behalf.</li>
<li>You are responsible for obtaining any required consents from your customers before collecting and storing their information in the platform.</li>
<li>PilotHouse will not use End Customer Data for any purpose other than providing the Service to you.</li>
<li>Automated communications sent to your customers (appointment reminders, order updates, loyalty notifications) are sent on your behalf using contact information you have collected.</li>
</ul>

<h2>5. Payment Processing</h2>
<p>All subscription billing and payment transactions are processed through Stripe, a PCI-compliant payment processor. We do not store your full credit card number, expiration date, or CVV. Please review <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer">Stripe's Privacy Policy</a> for information about how they handle your payment data.</p>

<h2>6. Communication Preferences</h2>
<p>You can manage your communication preferences at any time through your account settings:</p>
<ul>
<li><strong>Marketing Emails:</strong> Opt out via your profile settings or the unsubscribe link in any marketing email.</li>
<li><strong>SMS Notifications:</strong> Reply STOP to any text message to opt out.</li>
<li><strong>Push Notifications:</strong> Manage through your browser or device settings.</li>
<li><strong>Transactional Messages:</strong> Billing receipts, security alerts, and account notices cannot be opted out of as they are necessary for service delivery.</li>
</ul>

<h2>7. Data Sharing</h2>
<p>We do not sell your personal information or Tenant Data. We share data only as necessary to operate the Service:</p>
<ul>
<li><strong>Stripe:</strong> For subscription billing and payment processing</li>
<li><strong>SendGrid:</strong> For sending transactional and marketing emails</li>
<li><strong>Twilio:</strong> For sending SMS notifications</li>
<li><strong>Google Calendar:</strong> For appointment scheduling integrations (when enabled)</li>
<li><strong>Neon / PostgreSQL:</strong> For secure, encrypted database storage</li>
</ul>
<p>These service providers are bound by their own privacy policies and data processing agreements, and are only permitted to use your information as necessary to provide services to us.</p>
<p>We may also disclose information when required by law, court order, or to protect the rights, property, or safety of PilotHouse, our Subscribers, or the public.</p>

<h2>8. Data Security</h2>
<p>We implement appropriate technical and organizational security measures to protect your information, including encrypted connections (HTTPS/TLS), secure password hashing, token-based authentication with version invalidation, rate limiting on authentication endpoints, and tenant-level data isolation ensuring each business's data is inaccessible to other tenants. However, no method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.</p>

<h2>9. Data Retention</h2>
<ul>
<li>We retain your account and Tenant Data for as long as your subscription is active.</li>
<li>Upon account cancellation, you may request a data export within 30 days. After that period, your data may be permanently deleted from our systems.</li>
<li>Billing records and transaction logs may be retained for up to 7 years for legal and financial compliance purposes.</li>
<li>You may request deletion of your personal account information by contacting us through the Support page.</li>
</ul>

<h2>10. Children's Privacy</h2>
<p>The PilotHouse platform is a business tool intended for use by adults. It is not directed to children under 13. We do not knowingly collect personal information from children under 13. If you believe we have inadvertently collected such information, please contact us immediately.</p>

<h2>11. Your Rights</h2>
<p>Depending on your jurisdiction, you may have rights regarding your personal information, including the right to access, correct, or delete your data. To exercise these rights, contact us through the Support page within the app. We will respond to valid requests within 30 days.</p>

<h2>12. Changes to This Policy</h2>
<p>We may update this Privacy Policy from time to time. We will notify active Subscribers of material changes via email or in-app notice at least 14 days before the changes take effect. Continued use of the Service after the effective date constitutes acceptance of the updated policy.</p>

<h2>13. Contact Us</h2>
<p>If you have questions about this Privacy Policy or how we handle your data, please contact us through the Support page within the app.</p>`;

export default function PrivacyPolicy() {
  const [, navigate] = useLocation();

  const { data: page } = useQuery<{ content: string; title: string; updatedAt: string }>({
    queryKey: ['/api/legal', 'privacy-policy'],
    queryFn: async () => {
      const res = await fetch('/api/legal/privacy-policy');
      if (!res.ok) return null;
      return res.json();
    },
  });

  const content = page?.content || DEFAULT_CONTENT;

  return (
    <div className="min-h-screen bg-white pb-20">
      <div className="bg-gradient-to-r from-gray-900 to-gray-800 text-white p-4 sticky top-0 z-10">
        <div className="flex items-center gap-3">
          <button onClick={() => navigate(-1 as any)} className="p-1">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <h1 className="text-lg font-bold">Privacy Policy</h1>
        </div>
      </div>

      <div
        className="p-4 text-sm text-gray-700 leading-relaxed legal-content"
        dangerouslySetInnerHTML={{ __html: content }}
      />
    </div>
  );
}
