name: AnimalHousePetStore
options:
  bundleIdPrefix: com.animalhouseexperience
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    ENABLE_BITCODE: NO
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 2

targets:
  AnimalHousePetStore:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.animalhouseexperience.app
        PRODUCT_NAME: AnimalHousePetStore
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 2
