import { Pool } from '@neondatabase/serverless';
import ws from 'ws';
import { neonConfig } from '@neondatabase/serverless';

neonConfig.webSocketConstructor = ws;

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const FROMM_INGREDIENTS: Record<string, string> = {
  "Ancient 15lb": "Chicken, Chicken Meal, Whole Grain Sorghum, Chicken Broth, Whole Barley, Whole Oats, Pearled Barley, Chicken Fat (preserved with mixed tocopherols), Menhaden Fish Meal, Dried Tomato Pomace, Dried Egg Product, Dried Yeast, Buckwheat, Spelt, Millet, Chicken Liver, Cheese, Salmon Oil (preserved with mixed tocopherols), Quinoa, Flaxseed, Salt, Carrots, Duck, Lamb, Sweet Potatoes, Celery, Monocalcium Phosphate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Pyridoxine Hydrochloride, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Chicory Root Extract, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate], Sorbic Acid (Preservative), Yucca Schidigera Extract, L-Tryptophan, Taurine, DL-Methionine, Sodium Selenite, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Beef & Barley 12.2oz": "Beef, Beef Broth, Beef Liver, Whole Barley, Potatoes, Carrots, Peas, Pork, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Beef & Sweet Potato 12.2oz": "Beef, Beef Broth, Beef Liver, Sweet Potatoes, Lentils, Carrots, Pork, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Chicken À La Veg": "Chicken, Chicken Broth, Chicken Meal, Oatmeal, Pearled Barley, Sweet Potatoes, Brown Rice, White Rice, Menhaden Fish Meal, Whole Oats, Dried Egg Product, Dried Tomato Pomace, Chicken Fat (preserved with mixed tocopherols), Salmon Oil (preserved with mixed tocopherols), Whole Barley, Millet, Cheese, Flaxseed, Potatoes, Dried Yeast, Chicken Liver, Carrots, Apples, Broccoli, Celery, Salt, Monosodium Phosphate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Chicory Root Extract, Chicken Cartilage, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate], Sorbic Acid (Preservative), Cranberries, Yucca Schidigera Extract, Blueberries, Sodium Selenite, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Salmon À La Veg": "Salmon, Salmon Meal, Fish Broth, Oatmeal, Brown Rice, Pearled Barley, Chicken Fat (preserved with mixed tocopherols), Dried Egg Product, Whole Oats, White Rice, Dried Tomato Pomace, Salmon Oil (preserved with mixed tocopherols), Millet, Sweet Potatoes, Potatoes, Chicken, Herring Meal, Whole Barley, Dried Yeast, Cheese, Flaxseed, Chicken Liver, Carrots, Apples, Broccoli, Celery, Monocalcium Phosphate, Calcium Sulfate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Pyridoxine Hydrochloride, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Salt, Chicory Root Extract, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate, Sodium Selenite], Sorbic Acid (Preservative), Cranberries, Yucca Schidigera Extract, Blueberries, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Cat Adult": "Chicken, Chicken Meal, Pearled Barley, White Rice, Salmon Meal, Chicken Fat (preserved with mixed tocopherols), Dried Tomato Pomace, Chicken Liver, Dried Egg Product, Potatoes, Duck, Salmon Oil (preserved with mixed tocopherols), Flaxseed, Natural Flavor, Brewers Dried Yeast, Dehydrated Alfalfa Meal, DL-Methionine, Vitamins [Potassium Chloride, Choline Chloride, Vitamin E Supplement, Niacin Supplement, Ascorbic Acid, Calcium Carbonate, Pyridoxine Hydrochloride, Vitamin A Supplement, Folic Acid, Calcium Pantothenate, Thiamine Mononitrate, Riboflavin Supplement, Vitamin D3 Supplement, Biotin, Vitamin B12 Supplement], Chicken Cartilage, Dried Chicory Root, Salt, Monosodium Phosphate, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate], Sorbic Acid (Preservative), Yucca Schidigera Extract, Sodium Selenite, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Chicken 12.2oz": "Chicken, Chicken Broth, Chicken Liver, Potatoes, Carrots, Flaxseed, Peas, Tomato Paste, Dried Egg Product, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Copper Sulfate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Xanthan Gum, Salt, Vitamins [Potassium Chloride, Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Chicken & Duck 12.2oz": "Chicken, Chicken Broth, Duck, Chicken Liver, Potatoes, Carrots, Peas, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Xanthan Gum, Salt, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Chicken & Rice 12.2oz": "Chicken, Chicken Broth, Chicken Liver, Brown Rice, Potatoes, Carrots, Peas, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Xanthan Gum, Salt, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Chicken & Sweet Potato 12.2oz": "Chicken, Chicken Broth, Chicken Liver, Sweet Potatoes, Lentils, Carrots, Peas, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Xanthan Gum, Salt, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Turkey 12.2oz": "Turkey, Turkey Broth, Turkey Liver, Whole Barley, Potatoes, Carrots, Peas, Pork, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Turkey & Pumpkin 12.2oz": "Turkey, Turkey Broth, Turkey Liver, Pumpkin, Carrots, Potatoes, Peas, Pork, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Salmon 12.2oz": "Salmon, Fish Broth, Whitefish, Salmon Meal, Sweet Potatoes, Potatoes, Carrots, Peas, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Lamb & Lentil 12.2oz": "Lamb, Lamb Broth, Lamb Liver, Lentils, Sweet Potatoes, Carrots, Peas, Pork, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Duck & Sweet Potato 12.2oz": "Duck, Duck Broth, Duck Liver, Sweet Potatoes, Lentils, Carrots, Peas, Pork, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Seafood 12.2oz": "Salmon, Fish Broth, Whitefish, Tuna, Sweet Potatoes, Potatoes, Carrots, Peas, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Turkey Duck & Sweet Potato 12.2oz": "Turkey, Turkey Broth, Duck, Turkey Liver, Sweet Potatoes, Carrots, Peas, Pork, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Venison & Beef 12.2oz": "Venison, Beef Broth, Beef, Venison Liver, Whole Barley, Potatoes, Carrots, Peas, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "White Fish & Lentil 12.2oz": "Whitefish, Fish Broth, Salmon, Whitefish Meal, Lentils, Sweet Potatoes, Carrots, Peas, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Pork & Applesauce 12.2oz": "Pork, Pork Broth, Pork Liver, Applesauce, Potatoes, Carrots, Peas, Tomato Paste, Minerals [Dicalcium Phosphate, Zinc Sulfate, Magnesium Sulfate, Ferrous Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Sodium Selenite, Calcium Iodate, Manganese Sulfate, Copper Proteinate, Manganese Proteinate], Salmon Oil (preserved with mixed tocopherols), Agar-Agar, Potassium Chloride, Salt, Xanthan Gum, Vitamins [Vitamin E Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin A Supplement, Biotin, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Vitamin D3 Supplement, Folic Acid].",
  
  "Chicken Frommage": "Chicken, Chicken Meal, Chicken Broth, Oatmeal, Pearled Barley, Brown Rice, White Rice, Menhaden Fish Meal, Whole Oats, Dried Egg Product, Dried Tomato Pomace, Chicken Fat (preserved with mixed tocopherols), Cheese, Salmon Oil (preserved with mixed tocopherols), Whole Barley, Millet, Flaxseed, Potatoes, Dried Yeast, Chicken Liver, Carrots, Apples, Broccoli, Celery, Salt, Monosodium Phosphate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Chicory Root Extract, Chicken Cartilage, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate], Sorbic Acid (Preservative), Cranberries, Yucca Schidigera Extract, Blueberries, Sodium Selenite, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Beef Frittata Veg": "Beef, Beef Broth, Beef Meal, Oatmeal, Lentils, Potatoes, Pearled Barley, White Rice, Brown Rice, Menhaden Fish Meal, Whole Oats, Dried Egg Product, Dried Tomato Pomace, Chicken Fat (preserved with mixed tocopherols), Salmon Oil (preserved with mixed tocopherols), Whole Barley, Millet, Cheese, Flaxseed, Dried Yeast, Beef Liver, Carrots, Apples, Broccoli, Celery, Salt, Monosodium Phosphate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Chicory Root Extract, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate], Sorbic Acid (Preservative), Cranberries, Yucca Schidigera Extract, Blueberries, Sodium Selenite, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Surf & Turf": "Salmon, Fish Broth, Chicken, Salmon Meal, Duck Meal, Lentils, Chickpeas, Peas, Pea Protein, Dried Tomato Pomace, Potatoes, Dried Egg Product, Chicken Fat (preserved with mixed tocopherols), Salmon Oil (preserved with mixed tocopherols), Flaxseed, Cheese, Dried Yeast, Chicken Liver, Carrots, Celery, Apples, Salt, Monosodium Phosphate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Chicory Root Extract, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate], Sorbic Acid (Preservative), Cranberries, Yucca Schidigera Extract, Blueberries, Sodium Selenite, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Trout": "Trout, Fish Broth, Whitefish, Trout Meal, Whitefish Meal, Oatmeal, Brown Rice, Pearled Barley, Chicken Fat (preserved with mixed tocopherols), White Rice, Dried Egg Product, Whole Oats, Dried Tomato Pomace, Salmon Oil (preserved with mixed tocopherols), Millet, Sweet Potatoes, Potatoes, Whole Barley, Dried Yeast, Cheese, Flaxseed, Liver, Carrots, Apples, Broccoli, Celery, Monocalcium Phosphate, Calcium Sulfate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Pyridoxine Hydrochloride, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Salt, Chicory Root Extract, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate, Sodium Selenite], Sorbic Acid (Preservative), Cranberries, Yucca Schidigera Extract, Blueberries, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Whitefish": "Whitefish, Fish Broth, Whitefish Meal, Potatoes, Oatmeal, Brown Rice, Pearled Barley, Chicken Fat (preserved with mixed tocopherols), Dried Egg Product, Whole Oats, White Rice, Dried Tomato Pomace, Salmon Oil (preserved with mixed tocopherols), Millet, Sweet Potatoes, Whole Barley, Dried Yeast, Cheese, Flaxseed, Liver, Carrots, Apples, Broccoli, Celery, Calcium Sulfate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Pyridoxine Hydrochloride, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Salt, Chicory Root Extract, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate, Sodium Selenite], Sorbic Acid (Preservative), Cranberries, Yucca Schidigera Extract, Blueberries, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Duck À La Veg": "Duck, Fish Broth, Duck Meal, Oatmeal, Pearled Barley, Sweet Potatoes, Brown Rice, White Rice, Menhaden Fish Meal, Whole Oats, Dried Egg Product, Dried Tomato Pomace, Chicken Fat (preserved with mixed tocopherols), Salmon Oil (preserved with mixed tocopherols), Whole Barley, Millet, Cheese, Flaxseed, Potatoes, Dried Yeast, Liver, Carrots, Apples, Broccoli, Celery, Salt, Monosodium Phosphate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Chicory Root Extract, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate], Sorbic Acid (Preservative), Cranberries, Yucca Schidigera Extract, Blueberries, Sodium Selenite, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Game Bird": "Turkey, Turkey Broth, Goose, Turkey Meal, Duck Meal, Oatmeal, Pearled Barley, Brown Rice, White Rice, Menhaden Fish Meal, Whole Oats, Dried Egg Product, Dried Tomato Pomace, Chicken Fat (preserved with mixed tocopherols), Salmon Oil (preserved with mixed tocopherols), Pheasant, Whole Barley, Millet, Cheese, Flaxseed, Potatoes, Dried Yeast, Liver, Carrots, Apples, Broccoli, Celery, Salt, Monosodium Phosphate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Chicory Root Extract, Chicken Cartilage, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Calcium Carbonate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate], Sorbic Acid (Preservative), Cranberries, Yucca Schidigera Extract, Blueberries, Sodium Selenite, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Hasen Duckenpfeffer": "Rabbit, Fish Broth, Duck, Rabbit Meal, Duck Meal, Peas, Potatoes, Lentils, Chickpeas, Dried Tomato Pomace, Dried Egg Product, Chicken Fat (preserved with mixed tocopherols), Salmon Oil (preserved with mixed tocopherols), Cheese, Flaxseed, Dried Yeast, Liver, Carrots, Celery, Apples, Salt, Monosodium Phosphate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Chicory Root Extract, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate], Sorbic Acid (Preservative), Cranberries, Yucca Schidigera Extract, Blueberries, Sodium Selenite, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
  
  "Zealambder": "Lamb, Fish Broth, Lamb Meal, Green Peas, Potatoes, Lentils, Chickpeas, Dried Tomato Pomace, Dried Egg Product, Chicken Fat (preserved with mixed tocopherols), Salmon Oil (preserved with mixed tocopherols), Cheese, Flaxseed, Dried Yeast, Lamb Liver, Carrots, Celery, Apples, Salt, Monocalcium Phosphate, Vitamins [Choline Chloride, Potassium Chloride, Vitamin E Supplement, Ascorbic Acid, Calcium Carbonate, Riboflavin Supplement, Niacin Supplement, Calcium Pantothenate, Vitamin A Supplement, Vitamin D3 Supplement, Biotin, Vitamin B12 Supplement, Thiamine Mononitrate, Folic Acid], Chicory Root Extract, Minerals [Zinc Sulfate, Manganese Sulfate, Ferrous Sulfate, Magnesium Sulfate, Zinc Proteinate, Iron Proteinate, Manganese Proteinate, Copper Sulfate, Magnesium Proteinate, Copper Proteinate, Calcium Iodate], Sorbic Acid (Preservative), Cranberries, Yucca Schidigera Extract, Blueberries, Sodium Selenite, Taurine, Dried Lactobacillus casei Fermentation Product, Dried Lactobacillus reuteri Fermentation Product, Dried Lactobacillus acidophilus Fermentation Product, Dried Lactobacillus plantarum Fermentation Product.",
};

async function updateFrommIngredients() {
  console.log('Updating Fromm products with verified ingredients...\n');
  
  const client = await pool.connect();
  try {
    const { rows } = await client.query(`
      SELECT id, name FROM supplies 
      WHERE name ILIKE '%fromm%'
      AND (ingredients LIKE '%Salmon, Fish Broth, Chicken, Salmon Meal%' 
           OR ingredients IS NULL 
           OR ingredients = '')
      ORDER BY name
    `);
    
    console.log(`Found ${rows.length} Fromm products needing ingredient updates\n`);
    
    let updated = 0;
    
    for (const row of rows) {
      let matchedIngredients = '';
      let matchKey = '';
      
      for (const [key, ingredients] of Object.entries(FROMM_INGREDIENTS)) {
        if (row.name.includes(key)) {
          matchedIngredients = ingredients;
          matchKey = key;
          break;
        }
      }
      
      if (matchedIngredients) {
        await client.query(
          `UPDATE supplies SET ingredients = $1 WHERE id = $2`,
          [matchedIngredients, row.id]
        );
        console.log(`✓ Updated: ${row.name} (matched "${matchKey}")`);
        updated++;
      } else {
        console.log(`- No match: ${row.name}`);
      }
    }
    
    console.log(`\n=== SUMMARY ===`);
    console.log(`Total products checked: ${rows.length}`);
    console.log(`Updated with ingredients: ${updated}`);
    
  } finally {
    client.release();
  }
  
  process.exit(0);
}

updateFrommIngredients().catch(console.error);
